/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manufacturer;

/**
 *
 * @author preet
 */
public class AddMedicine extends javax.swing.JPanel {

    /**
     * Creates new form AddMedicine
     */
    public AddMedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddMed = new javax.swing.JLabel();
        lblMedName = new javax.swing.JLabel();
        lblMedContent = new javax.swing.JLabel();
        lblBaseComponent = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        txtNameMed = new javax.swing.JTextField();
        lblContent = new javax.swing.JTextField();
        txtBase = new javax.swing.JTextField();
        txtManuf = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblAddMed.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblAddMed.setText("Add Medicine");

        lblMedName.setText("Medicine Name");

        lblMedContent.setText("Key Content");

        lblBaseComponent.setText("Base Content");

        lblManufacturer.setText("Manufacturer");

        btnsave.setText("Save Medicine");

        btnBack.setText("<< Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedName)
                            .addComponent(lblMedContent)
                            .addComponent(lblBaseComponent)
                            .addComponent(lblManufacturer))
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnsave)
                            .addComponent(txtNameMed)
                            .addComponent(lblContent)
                            .addComponent(txtBase)
                            .addComponent(txtManuf, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(lblAddMed, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(418, 418, 418))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddMed, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMedName)
                    .addComponent(txtNameMed, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedContent)
                    .addComponent(lblContent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBaseComponent)
                    .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer)
                    .addComponent(txtManuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnsave)
                .addContainerGap(338, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel lblAddMed;
    private javax.swing.JLabel lblBaseComponent;
    private javax.swing.JTextField lblContent;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblMedContent;
    private javax.swing.JLabel lblMedName;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtManuf;
    private javax.swing.JTextField txtNameMed;
    // End of variables declaration//GEN-END:variables
}
