/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manufacturer;

/**
 *
 * @author preet
 */
public class ManufacturerViewInc extends javax.swing.JPanel {

    /**
     * Creates new form ManufacturerViewInc
     */
    public ManufacturerViewInc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lblMedicine = new javax.swing.JLabel();
        txtManuf = new javax.swing.JTextField();
        lblIncident = new javax.swing.JLabel();
        txtInc = new javax.swing.JTextField();
        lblManufacture = new javax.swing.JLabel();
        txtMedicine = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblOutcome = new javax.swing.JLabel();
        lblEventdateoccured = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        lblSideEffectswitness = new javax.swing.JLabel();
        txtSideEffects = new javax.swing.JTextField();
        lblDiagnosisNoteDoc = new javax.swing.JLabel();
        txtDiagnosis = new javax.swing.JTextField();
        lblOutcomesDoc = new javax.swing.JLabel();
        txtOutcome = new javax.swing.JTextField();
        lbl_severityAssigned = new javax.swing.JLabel();
        txtassigned = new javax.swing.JTextField();
        btnLabRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jSplitPane1.setPreferredSize(new java.awt.Dimension(300, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(250, 650));

        lblMedicine.setText("Medicine");

        lblIncident.setText("Incident No.");

        lblManufacture.setText("Manufacturer ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManufacture)
                            .addComponent(lblMedicine))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedicine, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtManuf)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIncident)
                        .addGap(42, 42, 42)
                        .addComponent(txtInc, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIncident)
                    .addComponent(txtInc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacture)
                    .addComponent(txtManuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        lblOutcome.setText("Outcome Attributed to ADVERSE EVENT-- Manufacturer View");

        lblEventdateoccured.setText("Date of event occured");

        lblSideEffectswitness.setText("Side Effects Witnessed");

        txtSideEffects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSideEffectsActionPerformed(evt);
            }
        });

        lblDiagnosisNoteDoc.setText("Diagnosis Note");

        lblOutcomesDoc.setText("Outcome from Doctors Report");

        lbl_severityAssigned.setText("Assigned Severity");

        txtassigned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtassignedActionPerformed(evt);
            }
        });

        btnLabRequest.setText("Request Test to Manufacture Lab");

        btnBack.setText("<<Back");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(lblOutcome))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLabRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEventdateoccured)
                                    .addComponent(lblSideEffectswitness)
                                    .addComponent(lblDiagnosisNoteDoc)
                                    .addComponent(lblOutcomesDoc)
                                    .addComponent(lbl_severityAssigned))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtassigned, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(txtSideEffects)
                                    .addComponent(txtDiagnosis)
                                    .addComponent(txtOutcome)
                                    .addComponent(txtdate))))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEventdateoccured)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSideEffectswitness)
                    .addComponent(txtSideEffects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiagnosisNoteDoc)
                    .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOutcomesDoc)
                    .addComponent(txtOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_severityAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtassigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(btnLabRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSideEffectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSideEffectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSideEffectsActionPerformed

    private void txtassignedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtassignedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtassignedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLabRequest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblDiagnosisNoteDoc;
    private javax.swing.JLabel lblEventdateoccured;
    private javax.swing.JLabel lblIncident;
    private javax.swing.JLabel lblManufacture;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblOutcome;
    private javax.swing.JLabel lblOutcomesDoc;
    private javax.swing.JLabel lblSideEffectswitness;
    private javax.swing.JLabel lbl_severityAssigned;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextField txtInc;
    private javax.swing.JTextField txtManuf;
    private javax.swing.JTextField txtMedicine;
    private javax.swing.JTextField txtOutcome;
    private javax.swing.JTextField txtSideEffects;
    private javax.swing.JTextField txtassigned;
    private javax.swing.JTextField txtdate;
    // End of variables declaration//GEN-END:variables
}
