/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sanjalinagare
 */
public class LabTest extends javax.swing.JPanel {

    /**
     * Creates new form LabTest
     */
    private EcoSystem system;
      private JPanel container;


    public LabTest(JPanel container, EcoSystem system) {
        initComponents();
        this.system=system;
        this.container=container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lab_Label = new javax.swing.JLabel();
        Blood_label = new javax.swing.JLabel();
        BloodTest_Text = new javax.swing.JTextField();
        Sugar_Label = new javax.swing.JLabel();
        Sugar_text = new javax.swing.JTextField();
        Liver_Label = new javax.swing.JLabel();
        Liver_Text = new javax.swing.JTextField();
        BoneDensity_Label = new javax.swing.JLabel();
        BoneDesnisty_Text = new javax.swing.JTextField();
        Kidney_Label = new javax.swing.JLabel();
        Kideny_Text = new javax.swing.JTextField();
        CBC_Label = new javax.swing.JLabel();
        CBC_Text = new javax.swing.JTextField();
        Platelets_Label = new javax.swing.JLabel();
        Platelets_Text = new javax.swing.JTextField();
        Report_Label = new javax.swing.JButton();

        Lab_Label.setText("Lab Test ");

        Blood_label.setText("Blood Test");

        Sugar_Label.setText("Sugar Test");

        Sugar_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sugar_textActionPerformed(evt);
            }
        });

        Liver_Label.setText("Liver Test");

        BoneDensity_Label.setText("Bone Density Test");

        BoneDesnisty_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoneDesnisty_TextActionPerformed(evt);
            }
        });

        Kidney_Label.setText("Kidney Test");

        CBC_Label.setText("CBC Test");

        Platelets_Label.setText("Platelets Test");

        Report_Label.setText("Report");
        Report_Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Report_LabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(Lab_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Platelets_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Kidney_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BoneDensity_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Liver_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Blood_label, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(Sugar_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CBC_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BloodTest_Text)
                            .addComponent(Sugar_text)
                            .addComponent(Liver_Text)
                            .addComponent(BoneDesnisty_Text)
                            .addComponent(Kideny_Text)
                            .addComponent(Platelets_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(CBC_Text)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(Report_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(423, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Lab_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Blood_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BloodTest_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sugar_Label)
                    .addComponent(Sugar_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Liver_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Liver_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BoneDensity_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(BoneDesnisty_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kidney_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kideny_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBC_Label)
                    .addComponent(CBC_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Platelets_Label)
                    .addComponent(Platelets_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(Report_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Sugar_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sugar_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sugar_textActionPerformed

    private void BoneDesnisty_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoneDesnisty_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoneDesnisty_TextActionPerformed

    private void Report_LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Report_LabelActionPerformed
        // TODO add your handling code here:
        RequestTestJPanel panel = new RequestTestJPanel(container, system);
        container.add("RequestTestJPanel", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_Report_LabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BloodTest_Text;
    private javax.swing.JLabel Blood_label;
    private javax.swing.JLabel BoneDensity_Label;
    private javax.swing.JTextField BoneDesnisty_Text;
    private javax.swing.JLabel CBC_Label;
    private javax.swing.JTextField CBC_Text;
    private javax.swing.JTextField Kideny_Text;
    private javax.swing.JLabel Kidney_Label;
    private javax.swing.JLabel Lab_Label;
    private javax.swing.JLabel Liver_Label;
    private javax.swing.JTextField Liver_Text;
    private javax.swing.JLabel Platelets_Label;
    private javax.swing.JTextField Platelets_Text;
    private javax.swing.JButton Report_Label;
    private javax.swing.JLabel Sugar_Label;
    private javax.swing.JTextField Sugar_text;
    // End of variables declaration//GEN-END:variables
}
