/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.EcoSystem;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;


/**
 *
 * @author preet
 */
public class PrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrescriptionJPanel
     */
   private EcoSystem system;
      private JPanel container;
      

 public   PrescriptionJPanel(JPanel container, EcoSystem system) {
        initComponents();
         this.container=container;
        this.system=system;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrescription = new javax.swing.JLabel();
        PatientName_Label = new javax.swing.JLabel();
        Age_Label = new javax.swing.JLabel();
        MedicinePrescribed_Label = new javax.swing.JLabel();
        PatientID_label = new javax.swing.JLabel();
        PatientID_Text = new javax.swing.JTextField();
        PatientName_Text = new javax.swing.JTextField();
        Age_Text = new javax.swing.JTextField();
        MedicinePrescribed_Text = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        EditPrescriptionBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblPrescription.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPrescription.setText("Prescription");

        PatientName_Label.setText("Patient Name");

        Age_Label.setText("Age");

        MedicinePrescribed_Label.setText("Medicine Prescribed");

        PatientID_label.setText("Patient ID");

        SaveBtn.setText("Save Prescription");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        EditPrescriptionBtn.setText("Edit Prescription");
        EditPrescriptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPrescriptionBtnActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(200, 200, 200)
                        .addComponent(lblPrescription))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(MedicinePrescribed_Label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(MedicinePrescribed_Text))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PatientID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PatientName_Label)
                                        .addComponent(Age_Label))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Age_Text)
                                        .addComponent(PatientName_Text)
                                        .addComponent(PatientID_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SaveBtn)
                                .addGap(80, 80, 80)
                                .addComponent(EditPrescriptionBtn)))))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrescription)
                    .addComponent(btnBack))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientID_label)
                    .addComponent(PatientID_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientName_Label)
                    .addComponent(PatientName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age_Label)
                    .addComponent(Age_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicinePrescribed_Label)
                    .addComponent(MedicinePrescribed_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtn)
                    .addComponent(EditPrescriptionBtn))
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
                   PatientID_Text.setEditable(false);
            PatientName_Text.setEditable(false);
            Age_Text.setEditable(false);
            MedicinePrescribed_Text.setEnabled(false);
            
                try{
            
            if(PatientName_Text.getText().isEmpty())
            {
            JOptionPane.showMessageDialog(null, "Name cant be null ");
            return;
            }
            }
        catch(NullPointerException e)
        {
        JOptionPane.showMessageDialog(null, "Please Enter Valid name");
            return;
        }
        
        
        

         try {
           Integer.parseInt(PatientID_Text.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Number cant be null ");
                throw e;
        }    
         
         
        
        try {
             Double.parseDouble(Age_Text.getText());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type the number for Age");            
            throw e;
        }
        
        try{
            
            if(MedicinePrescribed_Text.getText().isEmpty())
            {
            JOptionPane.showMessageDialog(null, "Name cant be null ");
            return;
            }
            }
        catch(NullPointerException e)
        {
        JOptionPane.showMessageDialog(null, "Please Enter Valid name");
            return;
        }

        
//                    object.setName(PatientName_Text.getText());
//            object.setPrice(Double.parseDouble(PatientID_Text.getText()));
//            probjectduct.setAvailNum(Integer.parseInt(Age_Text.getText()));
//            object.setDescription(MedicinePrescribed_Text.getText());
//             object.setEnabled(false);
//            btnUpdate.setEnabled(true);
        
            JOptionPane.showMessageDialog(null, "Account updated successfully"); 
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void EditPrescriptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPrescriptionBtnActionPerformed
        PatientID_Text.setEditable(false);
            PatientName_Text.setEditable(false);
            Age_Text.setEditable(false);
            MedicinePrescribed_Text.setEnabled(false);
            
            
//            object.setPrice(Double.parseDouble(PatientID_Text.getText()));
//            probjectduct.setAvailNum(Integer.parseInt(Age_Text.getText()));
//            object.setDescription(MedicinePrescribed_Text.getText());
//             object.setEnabled(false);
            
             JOptionPane.showMessageDialog(null, "Account Created Successfully");
    }//GEN-LAST:event_EditPrescriptionBtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
          container.remove(this);
         Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
       // sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age_Label;
    private javax.swing.JTextField Age_Text;
    private javax.swing.JButton EditPrescriptionBtn;
    private javax.swing.JLabel MedicinePrescribed_Label;
    private javax.swing.JTextField MedicinePrescribed_Text;
    private javax.swing.JTextField PatientID_Text;
    private javax.swing.JLabel PatientID_label;
    private javax.swing.JLabel PatientName_Label;
    private javax.swing.JTextField PatientName_Text;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblPrescription;
    // End of variables declaration//GEN-END:variables
}
