/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author preet
 */
public class ViewAppointment extends javax.swing.JPanel {
    private JPanel container;
    private EcoSystem system;
    /**
     * Creates new form ViewAppointment
     */
   

    public ViewAppointment(JPanel container, EcoSystem system) {
       initComponents(); 
          this.container=container;
          this.system=system; //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lbl_viewPatient = new javax.swing.JLabel();
        lbl_PatientName = new javax.swing.JLabel();
        txt_PatientID = new javax.swing.JTextField();
        lblPatientName = new javax.swing.JLabel();
        txt_PatientName = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        txt_Dobirth = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txt_Add = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        btnSave = new javax.swing.JToggleButton();
        Update = new javax.swing.JButton();

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbl_viewPatient.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_viewPatient.setText("View Appointment");

        lbl_PatientName.setText("Appointment ID");

        txt_PatientID.setEnabled(false);

        lblPatientName.setText("Patient Name");

        txt_PatientName.setEnabled(false);

        lblDob.setText("Date of Birth");

        txt_Dobirth.setEnabled(false);

        lblAddress.setText("Date");

        txt_Add.setEnabled(false);

        txt_age.setEnabled(false);

        lblAge.setText("Appointment Time");

        btnSave.setText("Save");

        Update.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_PatientName)
                        .addComponent(lblPatientName)
                        .addComponent(lblDob)
                        .addComponent(lblAddress)
                        .addComponent(lblAge)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_PatientID, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(txt_PatientName)
                    .addComponent(txt_Dobirth)
                    .addComponent(txt_Add)
                    .addComponent(txt_age)
                    .addComponent(Update))
                .addGap(461, 461, 461))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(btnBack)
                .addGap(101, 101, 101)
                .addComponent(lbl_viewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_viewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PatientName)
                    .addComponent(txt_PatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_PatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Dobirth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddress)
                    .addComponent(txt_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(Update))
                .addGap(265, 265, 265))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JButton btnBack;
    private javax.swing.JToggleButton btnSave;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lbl_PatientName;
    private javax.swing.JLabel lbl_viewPatient;
    private javax.swing.JTextField txt_Add;
    private javax.swing.JTextField txt_Dobirth;
    private javax.swing.JTextField txt_PatientID;
    private javax.swing.JTextField txt_PatientName;
    private javax.swing.JTextField txt_age;
    // End of variables declaration//GEN-END:variables
}
