/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author preet
 */
public class ViewPatientJPanel extends javax.swing.JPanel {
     private JPanel container;
     private EcoSystem system;
    /**
     * Creates new form ViewPatientJPanel
     */
    

    ViewPatientJPanel(JPanel container, EcoSystem system) {
       initComponents();
       this.container=container;
       this.system=system;//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_viewPatientHistory = new javax.swing.JLabel();
        lbl_PatientName = new javax.swing.JLabel();
        txt_PatientID = new javax.swing.JTextField();
        lblPatientName = new javax.swing.JLabel();
        txt_PatientName = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        txt_Dobirth = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txt_Add = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        txt_Contact = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        txt_weight = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        btnSave = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JButton();

        lbl_viewPatientHistory.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_viewPatientHistory.setText("View Patient History");

        lbl_PatientName.setText("Patient ID");

        txt_PatientID.setEnabled(false);

        lblPatientName.setText("Patient Name");

        txt_PatientName.setEnabled(false);

        lblDob.setText("Date of Birth");

        txt_Dobirth.setEnabled(false);

        lblAddress.setText("Address");

        txt_Add.setEnabled(false);

        lblAge.setText("Age");

        txt_age.setEnabled(false);

        lblContact.setText("Contact Details");

        txt_Contact.setEnabled(false);

        lblWeight.setText("Weight");

        txt_weight.setEnabled(false);

        Update.setText("Update");

        btnSave.setText("Save");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(btnBack)
                        .addGap(101, 101, 101)
                        .addComponent(lbl_viewPatientHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_PatientName)
                                .addComponent(lblPatientName)
                                .addComponent(lblDob)
                                .addComponent(lblAddress)
                                .addComponent(lblAge)
                                .addComponent(lblContact)
                                .addComponent(lblWeight)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_Contact)
                                .addComponent(txt_PatientID)
                                .addComponent(txt_PatientName)
                                .addComponent(txt_Dobirth)
                                .addComponent(txt_Add)
                                .addComponent(txt_age)
                                .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Update))))
                .addGap(461, 461, 461))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_viewPatientHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PatientName)
                    .addComponent(txt_PatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_PatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Dobirth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddress)
                    .addComponent(txt_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContact)
                    .addComponent(txt_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWeight)
                    .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(Update))
                .addGap(215, 215, 215))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

            // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JButton btnBack;
    private javax.swing.JToggleButton btnSave;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lbl_PatientName;
    private javax.swing.JLabel lbl_viewPatientHistory;
    private javax.swing.JTextField txt_Add;
    private javax.swing.JTextField txt_Contact;
    private javax.swing.JTextField txt_Dobirth;
    private javax.swing.JTextField txt_PatientID;
    private javax.swing.JTextField txt_PatientName;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables
}
