/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Incident;

/**
 *
 * @author sanjalinagare
 */
public class IncidentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IncidentJPanel
     */
    public IncidentJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IncidentCreat = new javax.swing.JLabel();
        IncidentNo_Label = new javax.swing.JLabel();
        IncidentNo_Text = new javax.swing.JTextField();
        Doctor_Label = new javax.swing.JLabel();
        Doctor_Text = new javax.swing.JTextField();
        PatientName_Label = new javax.swing.JLabel();
        PatientName_Text = new javax.swing.JTextField();
        PrescriptionGiven_Label = new javax.swing.JLabel();
        Prescription_Text = new javax.swing.JTextField();
        DatePrescription_Label = new javax.swing.JLabel();
        IssueDate_Text = new javax.swing.JTextField();
        MedicineTaken_Label = new javax.swing.JLabel();
        MedicineTaken_Text = new javax.swing.JTextField();
        Manufacturer_Label = new javax.swing.JLabel();
        Manufacture_Text = new javax.swing.JTextField();
        MedicineType_Label = new javax.swing.JLabel();
        MedicineType_Text = new javax.swing.JTextField();
        PatientAge_Label = new javax.swing.JLabel();
        PatientAge_Text = new javax.swing.JTextField();
        PatientGender_Label = new javax.swing.JLabel();
        MaleRadiobtn = new javax.swing.JRadioButton();
        FemaleRadiobtn = new javax.swing.JRadioButton();
        MedicalHistory_Label = new javax.swing.JLabel();
        MedicalHistory_Text = new javax.swing.JTextField();
        ProdAvail_Label = new javax.swing.JLabel();
        Yesbtn = new javax.swing.JRadioButton();
        Nobtn = new javax.swing.JRadioButton();
        SaveBtn = new javax.swing.JButton();
        NextBtn = new javax.swing.JButton();

        IncidentCreat.setText("Create Incient");

        IncidentNo_Label.setText("Incident_No");

        IncidentNo_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncidentNo_TextActionPerformed(evt);
            }
        });

        Doctor_Label.setText("Doctor");

        PatientName_Label.setText("Patient Name");

        PrescriptionGiven_Label.setText("Prescription Issued By");

        Prescription_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prescription_TextActionPerformed(evt);
            }
        });

        DatePrescription_Label.setText("Date Of Issue");

        IssueDate_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueDate_TextActionPerformed(evt);
            }
        });

        MedicineTaken_Label.setText("Medicine Taken");

        Manufacturer_Label.setText("Manufacture Name");

        MedicineType_Label.setText("Medicine Type");

        MedicineType_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineType_TextActionPerformed(evt);
            }
        });

        PatientAge_Label.setText("Patient Age");

        PatientGender_Label.setText("Gender");

        MaleRadiobtn.setText("Male");

        FemaleRadiobtn.setText("Female");

        MedicalHistory_Label.setText("Medical History");

        MedicalHistory_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalHistory_TextActionPerformed(evt);
            }
        });

        ProdAvail_Label.setText("Medicine Available For Evaluation");

        Yesbtn.setText("Yes");
        Yesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesbtnActionPerformed(evt);
            }
        });

        Nobtn.setText("No");

        SaveBtn.setText("Save");

        NextBtn.setText("Next");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PatientGender_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(PatientAge_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(IncidentNo_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Doctor_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PatientName_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                                .addGap(93, 93, 93))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MedicineType_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Manufacturer_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MedicineTaken_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DatePrescription_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrescriptionGiven_Label)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ProdAvail_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MedicalHistory_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(52, 52, 52)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Doctor_Text, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IncidentNo_Text, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PatientName_Text, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Manufacture_Text, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MedicineType_Text, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PatientAge_Text)
                                .addComponent(IssueDate_Text)
                                .addComponent(MedicineTaken_Text)
                                .addComponent(Prescription_Text)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(MaleRadiobtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                    .addComponent(FemaleRadiobtn)
                                    .addGap(18, 18, 18))
                                .addComponent(MedicalHistory_Text))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Yesbtn)
                                .addGap(18, 18, 18)
                                .addComponent(Nobtn)
                                .addGap(149, 149, 149)
                                .addComponent(SaveBtn)
                                .addGap(18, 18, 18)
                                .addComponent(NextBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(IncidentCreat, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MedicalHistory_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IncidentCreat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncidentNo_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IncidentNo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Doctor_Label)
                            .addComponent(Doctor_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientAge_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientAge_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientGender_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaleRadiobtn)
                            .addComponent(FemaleRadiobtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrescriptionGiven_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Prescription_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DatePrescription_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IssueDate_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MedicineTaken_Label)
                            .addComponent(MedicineTaken_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Manufacturer_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Manufacture_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MedicineType_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MedicineType_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(MedicalHistory_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProdAvail_Label)
                            .addComponent(Yesbtn)
                            .addComponent(Nobtn))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveBtn)
                            .addComponent(NextBtn))
                        .addGap(17, 17, 17))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IncidentNo_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncidentNo_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncidentNo_TextActionPerformed

    private void Prescription_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prescription_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Prescription_TextActionPerformed

    private void IssueDate_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueDate_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IssueDate_TextActionPerformed

    private void MedicineType_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineType_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineType_TextActionPerformed

    private void MedicalHistory_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalHistory_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalHistory_TextActionPerformed

    private void YesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesbtnActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatePrescription_Label;
    private javax.swing.JLabel Doctor_Label;
    private javax.swing.JTextField Doctor_Text;
    private javax.swing.JRadioButton FemaleRadiobtn;
    private javax.swing.JLabel IncidentCreat;
    private javax.swing.JLabel IncidentNo_Label;
    private javax.swing.JTextField IncidentNo_Text;
    private javax.swing.JTextField IssueDate_Text;
    private javax.swing.JRadioButton MaleRadiobtn;
    private javax.swing.JTextField Manufacture_Text;
    private javax.swing.JLabel Manufacturer_Label;
    private javax.swing.JLabel MedicalHistory_Label;
    private javax.swing.JTextField MedicalHistory_Text;
    private javax.swing.JLabel MedicineTaken_Label;
    private javax.swing.JTextField MedicineTaken_Text;
    private javax.swing.JLabel MedicineType_Label;
    private javax.swing.JTextField MedicineType_Text;
    private javax.swing.JButton NextBtn;
    private javax.swing.JRadioButton Nobtn;
    private javax.swing.JLabel PatientAge_Label;
    private javax.swing.JTextField PatientAge_Text;
    private javax.swing.JLabel PatientGender_Label;
    private javax.swing.JLabel PatientName_Label;
    private javax.swing.JTextField PatientName_Text;
    private javax.swing.JLabel PrescriptionGiven_Label;
    private javax.swing.JTextField Prescription_Text;
    private javax.swing.JLabel ProdAvail_Label;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JRadioButton Yesbtn;
    // End of variables declaration//GEN-END:variables
}
