/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Incident;

/**
 *
 * @author sanjalinagare
 */
public class IncidentJPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form IncidentJPanel2
     */
    public IncidentJPanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabTest_Label = new javax.swing.JLabel();
        YesLabTest = new javax.swing.JRadioButton();
        NoLabTest = new javax.swing.JRadioButton();
        Event1_Label = new javax.swing.JLabel();
        YesEvent1Radio = new javax.swing.JRadioButton();
        NoEvent1Radio = new javax.swing.JRadioButton();
        Event2_Label = new javax.swing.JLabel();
        YesEvent2Radio = new javax.swing.JRadioButton();
        NoEvent2Radio = new javax.swing.JRadioButton();
        ExpireDate_Label = new javax.swing.JLabel();
        ExpireDate_Text = new javax.swing.JTextField();
        UploadPicture_Label = new javax.swing.JLabel();
        Picture_Text = new javax.swing.JTextField();
        UploadBtn = new javax.swing.JButton();
        SubmitBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();

        LabTest_Label.setText("Done any Lab Test");

        YesLabTest.setText("Yes");

        NoLabTest.setText("No");
        NoLabTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoLabTestActionPerformed(evt);
            }
        });

        Event1_Label.setText("Event Abated After Use Stopped or Dose Reduced?");

        YesEvent1Radio.setText("Yes");

        NoEvent1Radio.setText("No");
        NoEvent1Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoEvent1RadioActionPerformed(evt);
            }
        });

        Event2_Label.setText("Event Reappeared After Reintroduction?");

        YesEvent2Radio.setText("Yes");

        NoEvent2Radio.setText("No");

        ExpireDate_Label.setText("Expire Date");

        ExpireDate_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpireDate_TextActionPerformed(evt);
            }
        });

        UploadPicture_Label.setText("Upload Picture");

        Picture_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Picture_TextActionPerformed(evt);
            }
        });

        UploadBtn.setText("Upload");

        SubmitBtn.setText("Submit to FDA");

        BackBtn.setText("Back");

        ViewBtn.setText("View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Event2_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(YesEvent2Radio)
                        .addGap(45, 45, 45)
                        .addComponent(NoEvent2Radio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabTest_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(YesLabTest)
                        .addGap(26, 26, 26)
                        .addComponent(NoLabTest))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Event1_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(YesEvent1Radio)
                        .addGap(32, 32, 32)
                        .addComponent(NoEvent1Radio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExpireDate_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UploadPicture_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Picture_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addComponent(ExpireDate_Text)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(UploadBtn)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ViewBtn)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTest_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YesLabTest)
                    .addComponent(NoLabTest))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Event1_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YesEvent1Radio)
                    .addComponent(NoEvent1Radio))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Event2_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YesEvent2Radio)
                    .addComponent(NoEvent2Radio))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpireDate_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpireDate_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UploadPicture_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Picture_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UploadBtn))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitBtn)
                    .addComponent(BackBtn)
                    .addComponent(ViewBtn))
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NoLabTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoLabTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoLabTestActionPerformed

    private void NoEvent1RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoEvent1RadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoEvent1RadioActionPerformed

    private void ExpireDate_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpireDate_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpireDate_TextActionPerformed

    private void Picture_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Picture_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Picture_TextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Event1_Label;
    private javax.swing.JLabel Event2_Label;
    private javax.swing.JLabel ExpireDate_Label;
    private javax.swing.JTextField ExpireDate_Text;
    private javax.swing.JLabel LabTest_Label;
    private javax.swing.JRadioButton NoEvent1Radio;
    private javax.swing.JRadioButton NoEvent2Radio;
    private javax.swing.JRadioButton NoLabTest;
    private javax.swing.JTextField Picture_Text;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JButton UploadBtn;
    private javax.swing.JLabel UploadPicture_Label;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JRadioButton YesEvent1Radio;
    private javax.swing.JRadioButton YesEvent2Radio;
    private javax.swing.JRadioButton YesLabTest;
    // End of variables declaration//GEN-END:variables
}
