/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReceptionistRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ReceptionistOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author preet
 */
public class ReceptionLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionLoginJPanel
     */
    public ReceptionLoginJPanel() {
        initComponents();
    }

    public ReceptionLoginJPanel(JPanel userProcessContainer, UserAccount account, ReceptionistOrganization receptionistOrganization, Enterprise enterprise, Network network, EcoSystem business) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_PatientInfo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        SearchPatientCombo_Box = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_PatientHis = new javax.swing.JTable();
        btn_SearchHis = new javax.swing.JButton();
        btn_ViewP = new javax.swing.JButton();
        btn_delP = new javax.swing.JButton();
        lbl_PName = new javax.swing.JLabel();
        txt_PWeight = new javax.swing.JTextField();
        lbl_PDob = new javax.swing.JLabel();
        lbl_PAddress = new javax.swing.JLabel();
        lbl_PAge = new javax.swing.JLabel();
        lbl_PContact = new javax.swing.JLabel();
        lbl_PWeight = new javax.swing.JLabel();
        txtPatient_Name = new javax.swing.JTextField();
        txt_Pdob = new javax.swing.JTextField();
        txt_Paddress = new javax.swing.JTextField();
        lbl_PId = new javax.swing.JLabel();
        txt_Page = new javax.swing.JTextField();
        txt_PatientID = new javax.swing.JTextField();
        txt_PcontactDets = new javax.swing.JTextField();
        btn_CreateP = new javax.swing.JButton();
        btn_BookPAppointment = new javax.swing.JButton();

        label_PatientInfo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label_PatientInfo.setText("Patient Information");

        btnBack.setText("<<Back");

        SearchPatientCombo_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SearchPatientCombo_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientCombo_BoxActionPerformed(evt);
            }
        });

        tbl_PatientHis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Date of Birth", "Address", "Age", "Contact details", "Weight"
            }
        ));
        jScrollPane1.setViewportView(tbl_PatientHis);

        btn_SearchHis.setText("Search");

        btn_ViewP.setText("View Patient");

        btn_delP.setText("Delete Patient");

        lbl_PName.setText("Patient Name");

        lbl_PDob.setText("Date of Birth");

        lbl_PAddress.setText("Address");

        lbl_PAge.setText("Age");

        lbl_PContact.setText("Contact Details");

        lbl_PWeight.setText("Weight");

        lbl_PId.setText("Patient ID");

        btn_CreateP.setText("Create Patient");

        btn_BookPAppointment.setText("Book Appointment");
        btn_BookPAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BookPAppointmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnBack)
                .addGap(224, 224, 224)
                .addComponent(label_PatientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 179, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_PId)
                                    .addComponent(lbl_PName)
                                    .addComponent(lbl_PDob)
                                    .addComponent(lbl_PAddress)
                                    .addComponent(lbl_PAge)
                                    .addComponent(lbl_PContact)
                                    .addComponent(lbl_PWeight))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_PcontactDets)
                                    .addComponent(txt_PatientID)
                                    .addComponent(txtPatient_Name)
                                    .addComponent(txt_Pdob)
                                    .addComponent(txt_Paddress)
                                    .addComponent(txt_Page)
                                    .addComponent(txt_PWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(250, 250, 250)
                                .addComponent(btn_CreateP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_BookPAppointment))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SearchPatientCombo_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btn_SearchHis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_ViewP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_delP)))
                        .addGap(123, 123, 123))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_PatientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchPatientCombo_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchHis)
                    .addComponent(btn_ViewP)
                    .addComponent(btn_delP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PId)
                    .addComponent(txt_PatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPatient_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_PName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PDob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Pdob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_PAddress)
                    .addComponent(txt_Paddress, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PAge)
                    .addComponent(txt_Page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_PContact)
                    .addComponent(txt_PcontactDets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_PWeight)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_PWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_CreateP)
                        .addComponent(btn_BookPAppointment)))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchPatientCombo_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPatientCombo_BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchPatientCombo_BoxActionPerformed

    private void btn_BookPAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BookPAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BookPAppointmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SearchPatientCombo_Box;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btn_BookPAppointment;
    private javax.swing.JButton btn_CreateP;
    private javax.swing.JButton btn_SearchHis;
    private javax.swing.JButton btn_ViewP;
    private javax.swing.JButton btn_delP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_PatientInfo;
    private javax.swing.JLabel lbl_PAddress;
    private javax.swing.JLabel lbl_PAge;
    private javax.swing.JLabel lbl_PContact;
    private javax.swing.JLabel lbl_PDob;
    private javax.swing.JLabel lbl_PId;
    private javax.swing.JLabel lbl_PName;
    private javax.swing.JLabel lbl_PWeight;
    private javax.swing.JTable tbl_PatientHis;
    private javax.swing.JTextField txtPatient_Name;
    private javax.swing.JTextField txt_PWeight;
    private javax.swing.JTextField txt_Paddress;
    private javax.swing.JTextField txt_Page;
    private javax.swing.JTextField txt_PatientID;
    private javax.swing.JTextField txt_PcontactDets;
    private javax.swing.JTextField txt_Pdob;
    // End of variables declaration//GEN-END:variables
}
